site_name: GTFS Realtime Best Practices
site_url: http://MobilityData.github.io/GTFS_Realtime_Best-Practices
repo_name: GTFS_Realtime_Best-Practices
repo_url: https://github.com/MobilityData/GTFS_Realtime_Best-Practices

# change directory names here
docs_dir: en
site_dir: site

theme:
  name: material

plugins:
    - search
    - macros

# close to mobilitydata color sorta maybe
palette:
  primary: '#301934'
  accent: 'purple'

# fun logos! see https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/
icon:
  logo: octicons/check-circle-24

font:
  text: 'Lato'
  code: 'Roboto Mono'

# give a title for each page
nav:
  - 'Introduction': 'index.md'
  - 'About': 'about.md'
  - 'General': 'general.md'
  - 'Feeds': "Feeds/index.md"
  - 'Messages': "Messages/index.md"
  - 'Use-cases': "Use-cases/index.md"
    
